package cli

const (
	usageFind                 = "usage: zot find <query> [--json] [--full] [--snippet] [--fulltext] [--fulltext-any] [--include-fields FIELD[,FIELD...]] [--item-type TYPE] [--tag TAG ...] [--tag-any] [--date-after YYYY[-MM[-DD]]] [--date-before YYYY[-MM[-DD]]] [--limit N] [--has-pdf] [--attachment-name TEXT] [--attachment-path TEXT] [--attachment-type TEXT] [--qmode titleCreatorYear|everything] [--include-trashed] | zot find --all [--json] [--full] [--snippet] [--include-fields FIELD[,FIELD...]] [--item-type TYPE] [--tag TAG ...] [--tag-any] [--date-after YYYY[-MM[-DD]]] [--date-before YYYY[-MM[-DD]]] [--limit N] [--has-pdf] [--attachment-name TEXT] [--attachment-path TEXT] [--attachment-type TEXT] [--qmode titleCreatorYear|everything] [--include-trashed]"
	usageShow                 = "usage: zot show <item-key> [--json] [--snippet]"
	usageExtractText          = "usage: zot extract-text <item-key> [--json]"
	usageExtractImages        = "usage: zot extract-images <item-key> [--output DIR] [--json]"
	usageRelate               = "usage: zot relate <item-key> [--json]"
	usageCite                 = "usage: zot cite <item-key> [--format citation|bib] [--style STYLE] [--locale LOCALE] [--json]"
	usageExport               = "usage: zot export <query> [--limit N] [--format bib|bibtex|biblatex|csljson|ris] [--json] | zot export --item-key KEY [--format bib|bibtex|biblatex|csljson|ris] [--json] | zot export --collection KEY [--format bib|bibtex|biblatex|csljson|ris] [--json]"
	usageCollections          = "usage: zot collections [--limit N] [--json]"
	usageNotes                = "usage: zot notes [--limit N] [--json]"
	usageTags                 = "usage: zot tags [--limit N] [--json]"
	usageSearches             = "usage: zot searches [--limit N] [--json]"
	usageDeleted              = "usage: zot deleted [--json]"
	usageStats                = "usage: zot stats [--json]"
	usageVersions             = "usage: zot versions <collections|searches|items|items-top> --since N [--include-trashed] [--if-modified-since-version N] [--json]"
	usageItemTypes            = "usage: zot item-types [--json]"
	usageItemFields           = "usage: zot item-fields [--json]"
	usageCreatorFields        = "usage: zot creator-fields [--json]"
	usageItemTypeFields       = "usage: zot item-type-fields <item-type> [--json]"
	usageItemTypeCreatorTypes = "usage: zot item-type-creator-types <item-type> [--json]"
	usageItemTemplate         = "usage: zot item-template <item-type> [--json]"
	usageKeyInfo              = "usage: zot key-info <api-key> [--json]"
	usageGroups               = "usage: zot groups [--json]"
	usageTrash                = "usage: zot trash [--limit N] [--json]"
	usageCollectionsTop       = "usage: zot collections-top [--json]"
	usagePublications         = "usage: zot publications [--limit N] [--json]"
	usageCreateItem           = "usage: zot create-item (--data JSON | --from-file PATH) --if-unmodified-since-version N [--json]"
	usageUpdateItem           = "usage: zot update-item <item-key> (--data JSON | --from-file PATH) --if-unmodified-since-version N [--json]"
	usageDeleteItem           = "usage: zot delete-item <item-key> --if-unmodified-since-version N [--json]"
	usageCreateItems          = "usage: zot create-items (--data JSON | --from-file PATH) --if-unmodified-since-version N [--json]"
	usageUpdateItems          = "usage: zot update-items (--data JSON | --from-file PATH) [--if-unmodified-since-version N] [--json]"
	usageDeleteItems          = "usage: zot delete-items --items KEY1,KEY2 [--if-unmodified-since-version N] [--json]"
	usageAddTag               = "usage: zot add-tag --items KEY1,KEY2 --tag TAG [--if-unmodified-since-version N] [--json]"
	usageRemoveTag            = "usage: zot remove-tag --items KEY1,KEY2 --tag TAG [--if-unmodified-since-version N] [--json]"
	usageCreateCollection     = "usage: zot create-collection (--data JSON | --from-file PATH) --if-unmodified-since-version N [--json]"
	usageUpdateCollection     = "usage: zot update-collection <collection-key> (--data JSON | --from-file PATH) [--if-unmodified-since-version N] [--json]"
	usageDeleteCollection     = "usage: zot delete-collection <collection-key> --if-unmodified-since-version N [--json]"
	usageCreateSearch         = "usage: zot create-search (--data JSON | --from-file PATH) --if-unmodified-since-version N [--json]"
	usageUpdateSearch         = "usage: zot update-search <search-key> (--data JSON | --from-file PATH) [--if-unmodified-since-version N] [--json]"
	usageDeleteSearch         = "usage: zot delete-search <search-key> --if-unmodified-since-version N [--json]"
)
